# Generated by Django 3.0.8 on 2020-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20200817_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='lin_item_total',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=10),
            preserve_default=False,
        ),
    ]
